### ISSUE TITLE
Update android rx example on site

### ISSUE THREAD

**Issue by ersin-ertan** [instacart/truetime-android#27] opened 2016-10-19 12:31 UTC
```java
TrueTimeRx.build().initialize(ntpHosts)
```
Should be
```java
TrueTimeRx.build().initializeRx(ntpHosts) // note the Rx
```

And perhaps add the ntpHosts string in the example so you don't have to open the sample app.

**Comment by kaushikgopal** [comment] 2016-10-19 16:17
I think the example here: https://github.com/instacart/truetime-android/blob/f5efdfff3f49b438678876ea946526d17b9e708b/app/src/main/java/com/instacart/library/sample/Sample2Activity.java already addresses that?

The vanilla version of the Sample https://github.com/instacart/truetime-android/blob/f5efdfff3f49b438678876ea946526d17b9e708b/app/src/main/java/com/instacart/library/sample/SampleActivity.java does not include/use Rx

**Comment by kaushikgopal** [comment] 2016-10-19 16:21
closing this out for now. feel free to re-open if my understanding of the issue is incorrect.

**Closed by kaushikgopal** 2016-10-19 16:21 UTC

**Comment by ersin-ertan** [comment] 2016-10-19 16:23
@kaushikgopal 
Sorry, Blog Post > Usage > Android

**Comment by kaushikgopal** [comment] 2016-10-19 16:32
ahhh. dang, good catch .

🙏, updated the blog post.
