### ISSUE TITLE
UndeliverableException ENETUNREACH (Network is unreachable)

### ISSUE THREAD

**Issue by jiyeh** [instacart/truetime-android#59] opened 2017-07-26 03:18 UTC
Running on latest version 3.3
```
compile 'com.github.instacart.truetime-android:library-extension-rx:3.3'
compile "io.reactivex.rxjava2:rxandroid:2.0.1"
```
We are experiencing crashes on this exception:
`Fatal Exception: io.reactivex.exceptions.UndeliverableException
java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)`

Full stack trace:
```
Fatal Exception: io.reactivex.exceptions.UndeliverableException: java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
       at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
       at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:604)
       at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:665)
       at io.reactivex.internal.operators.flowable.FlowableRetryPredicate$RepeatSubscriber.onError(FlowableRetryPredicate.java:81)
       at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onError(FlowableDoOnEach.java:110)
       at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onError(FlowableSubscribeOn.java:102)
       at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:268)
       at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:510)
       at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onError(FlowableCreate.java:461)
       at com.instacart.library.truetime.TrueTimeRx$4$1$2.subscribe(TrueTimeRx.java:201)
       at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:72)
       at io.reactivex.Flowable.subscribe(Flowable.java:12986)
       at io.reactivex.Flowable.subscribe(Flowable.java:12932)
       at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)
Caused by java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
       at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:550)
       at libcore.io.IoBridge.sendto(IoBridge.java:519)
       at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:182)
       at java.net.DatagramSocket.send(DatagramSocket.java:280)
       at com.instacart.library.truetime.SntpClient.requestTime(SntpClient.java:114)
       at com.instacart.library.truetime.TrueTime.requestTime(TrueTime.java:122)
       at com.instacart.library.truetime.TrueTimeRx$4$1$2.subscribe(TrueTimeRx.java:197)
       at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:72)
       at io.reactivex.Flowable.subscribe(Flowable.java:12986)
       at io.reactivex.Flowable.subscribe(Flowable.java:12932)
       at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)
Caused by libcore.io.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
       at libcore.io.Posix.sendtoBytes(Posix.java)
       at libcore.io.Posix.sendto(Posix.java:151)
       at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
       at libcore.io.IoBridge.sendto(IoBridge.java:517)
       at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:182)
       at java.net.DatagramSocket.send(DatagramSocket.java:280)
       at com.instacart.library.truetime.SntpClient.requestTime(SntpClient.java:114)
       at com.instacart.library.truetime.TrueTime.requestTime(TrueTime.java:122)
       at com.instacart.library.truetime.TrueTimeRx$4$1$2.subscribe(TrueTimeRx.java:197)
       at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:72)
       at io.reactivex.Flowable.subscribe(Flowable.java:12986)
       at io.reactivex.Flowable.subscribe(Flowable.java:12932)
       at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)
```

**Comment by kaushikgopal** [comment] 2017-08-03 03:59
hey @jiyeh,

it appears like this is an issue with the client wifi/network connectivity. we haven't seen this class of exception in our production use.

i did a quick search on the stack trace "SocketException: sendto failed: ENETUNREACH (Network is unreachable)" and saw this:

*  [problem is caused by the lack of an IP route to the target, not by coding problems](https://stackoverflow.com/questions/36092908/enetunreach-network-is-unreachable-error-what-am-i-doing-wroung)
* [wasn't connected to the Wi-Fi. It had no internet](https://stackoverflow.com/questions/19062836/android-network-is-unreachable-enetunreach)
* [Android couldnt create socket because it takes more time to make Wifi connection and ConnectivityManager checks only if the Wifi is turned on(checking for whether Wi-Fi is enabled, that doesn't necessarily mean that it's connected)](https://stackoverflow.com/questions/39999439/creating-a-socket-leads-to-network-is-unreachable-enetunreach)


almost all of these seem to indicate core network reachability problems. It might be helpful to track network connectivity on your app/client and checking to see if this could be the issue.

closing this out for now, but feel free to reopen if you have more data pointing to this not being a network problem.

**Closed by kaushikgopal** 2017-08-03 03:59 UTC

**Comment by abhishek-bharadwaj** [comment] 2018-01-15 05:37
Hey @kaushikgopal ,

This is happening to me as well. Any help will be appreciated.
