### ISSUE TITLE
Causes ANR and SocketTimeoutException on emulators

### ISSUE THREAD

**Issue by EdwardvanRaak** [instacart/truetime-android#68] opened 2017-09-19 14:53 UTC
Simply running the RxTrueTime sample2 on an Android emulator causes `java.net.SocketTimeoutException Poll timed out`. It's even causing ANR's inside my own project (also on emulators).

Tried this on 2 separate environments running emulators with different Android versions, they all show the same problem.

Everything works fine on my real devices. 

Is this expected behavior and can I ignore this or should this actually work?

Logs:
```

09-19 16:44:26.899 20496-21765/com.instacart.library.truetime D/TrueTimeRx: ---- resolving ntpHost : time.google.com
09-19 16:44:26.901 20496-21768/com.instacart.library.truetime D/TrueTimeRx: ---- requestTime from: 216.239.35.8
09-19 16:44:26.901 20496-21769/com.instacart.library.truetime D/TrueTimeRx: ---- requestTime from: 216.239.35.8
09-19 16:44:26.901 20496-21770/com.instacart.library.truetime D/TrueTimeRx: ---- requestTime from: 216.239.35.8
09-19 16:44:26.902 20496-21771/com.instacart.library.truetime D/TrueTimeRx: ---- requestTime from: 216.239.35.8
09-19 16:44:26.902 20496-21772/com.instacart.library.truetime D/TrueTimeRx: ---- requestTime from: 216.239.35.8
09-19 16:44:26.902 20496-21773/com.instacart.library.truetime D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:8::
09-19 16:44:26.903 20496-21774/com.instacart.library.truetime D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:8::
09-19 16:44:26.903 20496-21775/com.instacart.library.truetime D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:8::
09-19 16:44:26.903 20496-21776/com.instacart.library.truetime D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:8::
09-19 16:44:26.903 20496-21777/com.instacart.library.truetime D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:8::
```

Logs don't continue after that, it just loops forever and showing the SocketTimeoutException + causing the ANR.

**Comment by EdwardvanRaak** [comment] 2017-09-19 15:18
So I researched this a bit and if I understand correctly SNTP clients are simply not supported on emulators? Can anyone confirm this?

I tried out other SNTP client apps on my emulators and they also failed.¯\_(ツ)_/¯

**Comment by Seidak** [comment] 2017-09-20 12:26
It looks like I have the same problem for real device. Its Sony E5823. Any ideas what should we do? :)

**Comment by kaushikgopal** [comment] 2017-10-05 02:42
🤔 interestingly i'm noticing this behavior too now, on my emulator. This was not the case before. I used to be able to use SNTP before. Let me try snooping around and checking if there's something we can do.

sadly, if nothing comes out of this investigation, real devices have to be used i suppose 😞

**Comment by Seidak** [comment] 2017-10-05 12:24
@kaushikgopal but I've experienced the same problem on the real device as I mentioned above. :(

**Comment by kaushikgopal** [comment] 2017-10-05 19:50
@Seidak hmm.. can you provide more info. What ntp pool address are you hitting. can you post your exact stack trace. without more info, not sure how to help as i'm not seeing the same problem

**Comment by jksiezni** [comment] 2017-10-17 16:24
Hi, maybe it's not related to this issue particularly, but there is a bug in TrueTime that causes ANRs on every device.
The problem is with `synchronized` methods in SntpCient (886acc1b683e74569e6d96e8d94ab9e9a4f71e5d). Every time you try to call `TrueTime.isInitialized()` or `TrueTime.now()` on the main thread, it's blocked by `requestTime()`. It's a serious issue when the NTP server lags or don't even respond.

**Comment by lemberh** [comment] 2017-11-02 13:10
@jksiezni Look like you are right.
Quick fix would be to downgrade library version to 2.2, there it works for me

**Comment by kaushikgopal** [comment] 2017-11-02 15:10
@jksiezni @lemberh - i have an [internal branch "sync_to_atomic"](https://github.com/instacart/truetime-android/tree/kg/fix/sync_to_atomic) that should address that issue. I'm giving it a run in production internally before merging it to make sure it has an effect. it's looking promising so far.

feel free to give that a shot (you can point directly to the commit via jitpack).

i'll have that branch merged as soon as i gain some real world data. 🤞

**Comment by lemberh** [comment] 2017-11-02 18:21
@kaushikgopal I tried and so far it works great, @Seidak try version from the branch, maybe it will work for you,
And looks like this issue is also related https://github.com/instacart/truetime-android/issues/69

**Comment by fecogc** [comment] 2017-11-21 16:51
Hi @kaushikgopal I wasn't able to get the branch from jitpack.. Is this the correct brach name?

https://jitpack.io/#instacart/truetime-android/kg~fix/sync_to_atomic-SNAPSHOT

compile 'com.github.instacart.truetime-android:library-extension-rx:kg~fix'

**Comment by sreejithbnaick** [comment] 2018-01-12 19:30
IPv6 Addresses are timing out both on Emulator(Google) and Real Device(Xiaomi Note4), causing a long loop of retry. Filtering IPv4 address worked better for me. 

(FYI: I was running AndroidTest, not in a real application)

**Comment by Mugurell** [comment] 2018-01-24 13:52
@fecogc 
As per jitpack documentation - https://github.com/jitpack/jitpack.io/blob/master/FAQ.md
We can use `'com.github.instacart.truetime-android:library-extension-rx:kg~fix~sync_to_atomic-SNAPSHOT'` to get that branch compiled.

**Comment by chris6647** [comment] 2018-03-08 08:12
We have switched to https://github.com/AllanHasegawa/Tempo which, for now at least, has not given any of the issues we've had with truetime.

**Comment by kaushikgopal** [comment] 2018-05-28 23:37
PR #80 is up and should be merged shortly.

**Comment by kaushikgopal** [comment] 2018-05-29 00:58
`master` should have the required fixes now. If you're eager to take this before it hits `3.4` try:

`implementation com.github.instacart.truetime-android:library-extension-rx:09087b6a6e`

**Comment by atrifat** [comment] 2018-05-29 02:05
@kaushikgopal LGTM, finally merged. I have already implemented it on my project. Thanks.

**Closed** 2018-05-31 20:47 UTC
Labels: awaiting feedback

**Comment by kurilyonok** [comment] 2018-06-06 09:23
Hi @kaushikgopal ! I'm experiencing the same issue with slow wifi (( And emulators as well.. Looking forward to update version 3.4! Thanks man, great lib!

**Comment by MarkVillacampa** [comment] 2018-08-24 13:32
The original issue is not fixed. IPv6 addresses are not being resolved in the emulator and possibly in some devices as stated by @sreejithbnaick.

The problem mentioned in #337286921, for which this issue was closed, has been addressed, but it is not the original issue. Should I open a new open or can you reopen this one?

**Comment by apexkid** [comment] 2018-11-25 13:36
Facing this same issue in 3.4 version. Please suggest on how to resolve?

```
2018-11-25 19:02:07.102 19915-20096/com.tl.dialog D/SntpClient: ---- SNTP request failed for 2001:4860:4806:8::
2018-11-25 19:02:07.105 19915-20096/com.tl.dialog E/TrueTimeRx: ---- Error requesting time
    java.net.SocketTimeoutException: Poll timed out
        at libcore.io.IoBridge.poll(IoBridge.java:691)
        at java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:149)
        at java.net.PlainDatagramSocketImpl.receive0(PlainDatagramSocketImpl.java:140)
        at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:143)
        at java.net.DatagramSocket.receive(DatagramSocket.java:847)
        at com.instacart.library.truetime.SntpClient.requestTime(SntpClient.java:123)
        at com.instacart.library.truetime.TrueTime.requestTime(TrueTime.java:133)
        at com.instacart.library.truetime.TrueTimeRx$4$1$2.subscribe(TrueTimeRx.java:211)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:72)
        at io.reactivex.Flowable.subscribe(Flowable.java:14409)
        at io.reactivex.Flowable.subscribe(Flowable.java:14356)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```


Initialization code:
```
mTrueTime
                    .initializeRx("time.google.com")
                    .subscribeOn(Schedulers.io())
                    .subscribe(
                            date -> {
                                mIsInitializing = false;
                                Log.v(TAG, "TrueTime was initialized and we have a time: " + date);
                            },
                            throwable -> {
                                mIsInitializing = false;
                                Log.e(TAG, "NTP failed: ", throwable);
                            }
                    );
```

**Comment by anandwana001** [comment] 2018-11-26 05:51
I am also getting the same error

`implementation 'com.github.instacart.truetime-android:library-extension-rx:3.4'`

```
2018-11-26 11:09:01.870 25724-25791/com.doubtnutapp D/TrueTimeRx: ---- resolving ntpHost : time.google.com
2018-11-26 11:09:01.981 25724-25789/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.4
2018-11-26 11:09:01.992 25724-25796/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.4
2018-11-26 11:09:01.992 25724-25800/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.8
2018-11-26 11:09:01.992 25724-25797/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.4
2018-11-26 11:09:01.992 25724-25801/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.8
2018-11-26 11:09:01.992 25724-25802/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.8
2018-11-26 11:09:01.992 25724-25798/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.8
2018-11-26 11:09:01.993 25724-25795/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.4
2018-11-26 11:09:01.993 25724-25794/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.4
2018-11-26 11:09:01.993 25724-25799/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.8
2018-11-26 11:09:02.004 25724-25807/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.12
2018-11-26 11:09:02.004 25724-25808/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.0
2018-11-26 11:09:02.004 25724-25806/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.12
2018-11-26 11:09:02.006 25724-25805/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.12
2018-11-26 11:09:02.018 25724-25809/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.0
2018-11-26 11:09:02.023 25724-25804/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.12
2018-11-26 11:09:02.024 25724-25803/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.12
2018-11-26 11:09:02.037 25724-25810/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.0
2018-11-26 11:09:02.037 25724-25821/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806::
2018-11-26 11:09:02.039 25724-25820/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806::
2018-11-26 11:09:02.040 25724-25819/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806::
2018-11-26 11:09:02.042 25724-25818/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806::
2018-11-26 11:09:02.044 25724-25817/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:c::
2018-11-26 11:09:02.045 25724-25815/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:c::
2018-11-26 11:09:02.046 25724-25812/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.0
2018-11-26 11:09:02.048 25724-25814/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:c::
2018-11-26 11:09:02.054 25724-25813/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:c::
2018-11-26 11:09:02.054 25724-25811/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 216.239.35.0
2018-11-26 11:09:02.055 25724-25822/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806::
2018-11-26 11:09:02.058 25724-25823/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:4::
2018-11-26 11:09:02.060 25724-25824/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:4::
2018-11-26 11:09:02.061 25724-25825/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:4::
2018-11-26 11:09:02.061 25724-25826/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:4::
2018-11-26 11:09:02.062 25724-25816/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:c::
2018-11-26 11:09:02.069 25724-25827/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:4::
2018-11-26 11:09:02.076 25724-25828/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:8::
2018-11-26 11:09:02.080 25724-25829/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:8::
2018-11-26 11:09:02.117 25724-25831/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:8::
2018-11-26 11:09:02.118 25724-25832/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:8::
2018-11-26 11:09:02.119 25724-25830/com.doubtnutapp D/TrueTimeRx: ---- requestTime from: 2001:4860:4806:8::
2018-11-26 11:09:03.483 25724-25794/com.doubtnutapp D/TrueTimeRx: ---- filterLeastRoundTrip: [[J@340b625, [J@fab03fa, [J@4630dab, [J@9991c08, [J@2eb8fa1]
2018-11-26 11:09:04.131 25724-25798/com.doubtnutapp D/TrueTimeRx: ---- filterLeastRoundTrip: [[J@68db8c2, [J@aef6d3, [J@3e59210, [J@3a04109, [J@5029f0e]
2018-11-26 11:09:06.008 25724-25803/com.doubtnutapp D/TrueTimeRx: ---- filterLeastRoundTrip: [[J@cb5bda0, [J@2e8ad59, [J@db91d1e, [J@1e4b9ff, [J@94913cc]
2018-11-26 11:09:37.809 25724-25821/com.doubtnutapp E/TrueTimeRx: ---- Error requesting time
    java.net.SocketTimeoutException: Poll timed out
        at libcore.io.IoBridge.poll(IoBridge.java:691)
        at java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:149)
        at java.net.PlainDatagramSocketImpl.receive0(PlainDatagramSocketImpl.java:140)
        at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:143)
        at java.net.DatagramSocket.receive(DatagramSocket.java:847)
        at com.instacart.library.truetime.SntpClient.requestTime(SntpClient.java:123)
        at com.instacart.library.truetime.TrueTime.requestTime(TrueTime.java:133)
        at com.instacart.library.truetime.TrueTimeRx$4$1$2.subscribe(TrueTimeRx.java:211)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:72)
        at io.reactivex.Flowable.subscribe(Flowable.java:14409)
        at io.reactivex.Flowable.subscribe(Flowable.java:14356)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by apexkid** [comment] 2018-11-27 14:21
Any update?

**Comment by fecogc** [comment] 2018-11-28 00:15
> We have switched to https://github.com/AllanHasegawa/Tempo which, for now at least, has not given any of the issues we've had with truetime.

Like @chris6647 we have switched to Tempo..
