### ISSUE TITLE
Cant init Truetime in android. You need to call init() on TrueTime at least once

### ISSUE THREAD

**Issue by PalakDarjiHs** [instacart/truetime-android#45] opened 2017-02-28 10:52 UTC
First of all, I must tell you, there must be version number in description. I cant find it for gradle compile. I ended up with 2.2. Now, I am not able to init Truetime.. It gives me error

>  "You need to call init() on TrueTime at least once"

I tried apk of this lib from android arsenal.. Its not working. Can you plz help?

**Comment by kaushikgopal** [comment] 2017-04-06 18:51
hey @PalakDarjiHs. Thanks for the feedback. The [releases](https://github.com/instacart/truetime-android/releases) page typically has the changes against versions.

I don't exactly understand what your problem is. That error message basically means you're trying to access `TrueTime(Rx).now` without TrueTime actually having been initialized. 

Here's i would suggest:

* establish that the sample app that comes with this repo works. I would clone this repo directly for that testing. it's a standard Android Studio project, so shouldn't be difficult to get up and running
* are you using TrueTime or TrueTimeRx ? they are different and i usually suggest the latter.

if you can shoot some more info my way, we can try to debug this issue.

**Comment by kaushikgopal** [comment] 2017-05-04 17:20
closing this out for now. feel free to reopen if you have more feedback

**Closed by kaushikgopal** 2017-05-04 17:20 UTC

**Comment by abrekcoin** [comment] 2019-09-01 14:15
hey, ı am getting this error . this is how ı use true time :
 try {
            build().initialize();
        } catch (IOException e) {
            e.printStackTrace();
        }

        String timez =  TimeZone.getDefault().getDisplayName();

        try {
            TrueTime.build().initialize();
        } catch (IOException e) {
            e.printStackTrace();
        }

        Date myDate = TrueTime.now();


 and this ismy error:

Caused by: java.lang.IllegalStateException: You need to call init() on TrueTime at least once.
        at com.instacart.library.truetime.TrueTime.now(TrueTime.java:29)
        at com.filikapp.filika.live.onCreateView(live.java:62)


how can i call init() ?

**Comment by tushar40** [comment] 2019-11-18 11:30
@abrekcoin  getting the same issue !!

AsyncTask.execute(new Runnable() {
            @Override
            public void run() {

                try {
                    TrueTime.build().initialize();
                    Log.e(TAG,"Truetime has been initialized");
                } catch (IOException e) {
                    e.printStackTrace();
                }

            }
        });

**Comment by AwaisIslam** [comment] 2025-12-01 06:16
There's an issue in this library with the new version 4.0.0-alpha. We cannot use the implementation below with this latest version. However, it's working fine with version 3.5

CoroutineScope(Dispatchers.IO).launch {
      try {
        TrueTime.build().initialize()
      } catch (e: Exception) {
        e.printStackTrace()
      }
    }
